# Generated by Django 3.1.1 on 2020-09-18 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ap1person',
            name='age',
            field=models.IntegerField(),
        ),
    ]
