# Generated by Django 3.1.1 on 2020-10-26 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ap1', '0002_auto_20200918_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='midAdmin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='用户名')),
                ('pwd', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='电子邮箱')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号')),
                ('family_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='姓')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='名')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (2, '未知')], default=2, null=True, verbose_name='性别')),
                ('id_card', models.CharField(blank=True, max_length=255, null=True, verbose_name='身份证')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
            ],
        ),
        migrations.CreateModel(
            name='midBuilding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='楼栋名')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
            ],
        ),
        migrations.CreateModel(
            name='midCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='公司地址')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
            ],
        ),
        migrations.CreateModel(
            name='midUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='单元名')),
                ('lift', models.IntegerField(blank=True, choices=[(1010, '有'), (2020, '无')], default=2020, null=True, verbose_name='性别')),
                ('layer_count', models.IntegerField(blank=True, null=True, verbose_name='总楼层数')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
                ('building_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midbuilding', verbose_name='楼栋id')),
            ],
        ),
        migrations.CreateModel(
            name='midRoom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='房号')),
                ('layer', models.CharField(blank=True, max_length=255, null=True, verbose_name='楼层')),
                ('apartment', models.IntegerField(blank=True, null=True, verbose_name='户型')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
                ('building_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midbuilding', verbose_name='楼栋id')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midunit', verbose_name='单元id')),
            ],
        ),
        migrations.CreateModel(
            name='midInhabitant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='业主姓名')),
                ('sex', models.IntegerField(blank=True, choices=[(1, '男'), (0, '女'), (2, '未知')], default=2, null=True, verbose_name='性别')),
                ('birthday', models.CharField(blank=True, max_length=255, null=True, verbose_name='生日')),
                ('age', models.CharField(blank=True, max_length=255, null=True, verbose_name='年龄')),
                ('mobile', models.CharField(blank=True, max_length=255, null=True, verbose_name='联系手机')),
                ('ownerType', models.IntegerField(blank=True, choices=[(1002, '家庭成员'), (1001, '本人')], default=1001, null=True, verbose_name='与业主关系类型')),
                ('status', models.IntegerField(blank=True, choices=[(1, '有效'), (0, '无效')], default=0, null=True, verbose_name='状态')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
                ('building_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midbuilding', verbose_name='楼栋id')),
                ('community_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midcompany', verbose_name='小区id')),
                ('room_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midroom', verbose_name='房屋id')),
                ('unit_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midunit', verbose_name='单元id')),
            ],
        ),
        migrations.CreateModel(
            name='midCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('username', models.CharField(blank=True, max_length=255, null=True, verbose_name='小区名')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='小区地址')),
                ('nearly_by_landmarks', models.CharField(blank=True, max_length=255, null=True, verbose_name='附近地标')),
                ('longitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='经度')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True, verbose_name='维度')),
                ('city_code', models.IntegerField(blank=True, null=True, verbose_name='城市代码')),
                ('sync_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='同步类型')),
                ('corp_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midcompany', verbose_name='公司id')),
            ],
        ),
        migrations.AddField(
            model_name='midbuilding',
            name='community_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ap1.midcommunity', verbose_name='小区id'),
        ),
    ]
